src_language_list = [
    'Auto Detected',
    'Chinese',
    'English',
    'French',
    'German',
    'Hindi',
    'Italian',
    'Japanese',
    'Korean',
    'Portuguese',
    'Russian',
    'Swedish',
    'Thai',
    'Vietnamese',
]

src_language_code_dict = {
    'Auto Detected' : 'autodetect',
    'Chinese': 'zh',
    'English': 'en',
    'French': 'fr',
    'German': 'de',
    'Hindi': 'hi',
    'Italian': 'it',
    'Japanese': 'ja',
    'Korean': 'ko',
    'Portuguese': 'pt',
    'Russian': 'ru',
    'Swedish': 'sv',
    'Thai': 'th',
    'Vietnamese': 'vi',
}

dest_language_list = [
    'Chinese',
    'English',
    'French',
    'German',
    'Hindi',
    'Italian',
    'Japanese',
    'Korean',
    'Portuguese',
    'Russian',
    'Swedish',
    'Thai',
    'Vietnamese',
]

dest_language_code_dict = {
    'Chinese': 'zh',
    'English': 'en',
    'French': 'fr',
    'German': 'de',
    'Hindi': 'hi',
    'Italian': 'it',
    'Japanese': 'ja',
    'Korean': 'ko',
    'Portuguese': 'pt',
    'Russian': 'ru',
    'Swedish': 'sv',
    'Thai': 'th',
    'Vietnamese': 'vi',
}