

all:
	echo "\nBuild module importer"; cd importer; make; cd ..
	echo "\nBuild module operation"; cd operation; make; cd ..

clean:
	echo "\nClean module importer"; cd importer; make clean; cd ..
	echo "\nClean module operation"; cd operation; make clean; cd ..
