all:
	echo "\nBuild module TCP Server"; cd tcp_server; make; cd ..
	echo "\nBuild module TCP Client"; cd tcp_client; make; cd ..

clean:
	echo "\nClean module TCP Server"; cd tcp_server; make clean; cd ..
	echo "\nClean module TCP Client"; cd tcp_client; make clean; cd ..
