/**
 * Autogenerated by Thrift Compiler (0.15.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef extension_functions_TYPES_H
#define extension_functions_TYPES_H

#include <iosfwd>

#include <thrift/Thrift.h>
#include <thrift/TApplicationException.h>
#include <thrift/TBase.h>
#include <thrift/protocol/TProtocol.h>
#include <thrift/transport/TTransport.h>

#include <functional>
#include <memory>




struct TExtArgumentType {
  enum type {
    Int8 = 0,
    Int16 = 1,
    Int32 = 2,
    Int64 = 3,
    Float = 4,
    Double = 5,
    Void = 6,
    PInt8 = 7,
    PInt16 = 8,
    PInt32 = 9,
    PInt64 = 10,
    PFloat = 11,
    PDouble = 12,
    PBool = 13,
    Bool = 14,
    ArrayInt8 = 15,
    ArrayInt16 = 16,
    ArrayInt32 = 17,
    ArrayInt64 = 18,
    ArrayFloat = 19,
    ArrayDouble = 20,
    ArrayBool = 21,
    GeoPoint = 22,
    GeoLineString = 23,
    Cursor = 24,
    GeoPolygon = 25,
    GeoMultiPolygon = 26,
    ColumnInt8 = 27,
    ColumnInt16 = 28,
    ColumnInt32 = 29,
    ColumnInt64 = 30,
    ColumnFloat = 31,
    ColumnDouble = 32,
    ColumnBool = 33,
    TextEncodingNone = 34,
    TextEncodingDict8 = 35,
    TextEncodingDict16 = 36,
    TextEncodingDict32 = 37,
    ColumnListInt8 = 38,
    ColumnListInt16 = 39,
    ColumnListInt32 = 40,
    ColumnListInt64 = 41,
    ColumnListFloat = 42,
    ColumnListDouble = 43,
    ColumnListBool = 44
  };
};

extern const std::map<int, const char*> _TExtArgumentType_VALUES_TO_NAMES;

std::ostream& operator<<(std::ostream& out, const TExtArgumentType::type& val);

std::string to_string(const TExtArgumentType::type& val);

struct TOutputBufferSizeType {
  enum type {
    kConstant = 0,
    kUserSpecifiedConstantParameter = 1,
    kUserSpecifiedRowMultiplier = 2
  };
};

extern const std::map<int, const char*> _TOutputBufferSizeType_VALUES_TO_NAMES;

std::ostream& operator<<(std::ostream& out, const TOutputBufferSizeType::type& val);

std::string to_string(const TOutputBufferSizeType::type& val);

class TUserDefinedFunction;

class TUserDefinedTableFunction;

typedef struct _TUserDefinedFunction__isset {
  _TUserDefinedFunction__isset() : name(false), argTypes(false), retType(false) {}
  bool name :1;
  bool argTypes :1;
  bool retType :1;
} _TUserDefinedFunction__isset;

class TUserDefinedFunction : public virtual ::apache::thrift::TBase {
 public:

  TUserDefinedFunction(const TUserDefinedFunction&);
  TUserDefinedFunction& operator=(const TUserDefinedFunction&);
  TUserDefinedFunction() noexcept
                       : name(),
                         retType(static_cast<TExtArgumentType::type>(0)) {
  }

  virtual ~TUserDefinedFunction() noexcept;
  std::string name;
  std::vector<TExtArgumentType::type>  argTypes;
  /**
   * 
   * @see TExtArgumentType
   */
  TExtArgumentType::type retType;

  _TUserDefinedFunction__isset __isset;

  void __set_name(const std::string& val);

  void __set_argTypes(const std::vector<TExtArgumentType::type> & val);

  void __set_retType(const TExtArgumentType::type val);

  bool operator == (const TUserDefinedFunction & rhs) const
  {
    if (!(name == rhs.name))
      return false;
    if (!(argTypes == rhs.argTypes))
      return false;
    if (!(retType == rhs.retType))
      return false;
    return true;
  }
  bool operator != (const TUserDefinedFunction &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TUserDefinedFunction & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(TUserDefinedFunction &a, TUserDefinedFunction &b);

std::ostream& operator<<(std::ostream& out, const TUserDefinedFunction& obj);

typedef struct _TUserDefinedTableFunction__isset {
  _TUserDefinedTableFunction__isset() : name(false), sizerType(false), sizerArgPos(false), inputArgTypes(false), outputArgTypes(false), sqlArgTypes(false) {}
  bool name :1;
  bool sizerType :1;
  bool sizerArgPos :1;
  bool inputArgTypes :1;
  bool outputArgTypes :1;
  bool sqlArgTypes :1;
} _TUserDefinedTableFunction__isset;

class TUserDefinedTableFunction : public virtual ::apache::thrift::TBase {
 public:

  TUserDefinedTableFunction(const TUserDefinedTableFunction&);
  TUserDefinedTableFunction& operator=(const TUserDefinedTableFunction&);
  TUserDefinedTableFunction() noexcept
                            : name(),
                              sizerType(static_cast<TOutputBufferSizeType::type>(0)),
                              sizerArgPos(0) {
  }

  virtual ~TUserDefinedTableFunction() noexcept;
  std::string name;
  /**
   * 
   * @see TOutputBufferSizeType
   */
  TOutputBufferSizeType::type sizerType;
  int32_t sizerArgPos;
  std::vector<TExtArgumentType::type>  inputArgTypes;
  std::vector<TExtArgumentType::type>  outputArgTypes;
  std::vector<TExtArgumentType::type>  sqlArgTypes;

  _TUserDefinedTableFunction__isset __isset;

  void __set_name(const std::string& val);

  void __set_sizerType(const TOutputBufferSizeType::type val);

  void __set_sizerArgPos(const int32_t val);

  void __set_inputArgTypes(const std::vector<TExtArgumentType::type> & val);

  void __set_outputArgTypes(const std::vector<TExtArgumentType::type> & val);

  void __set_sqlArgTypes(const std::vector<TExtArgumentType::type> & val);

  bool operator == (const TUserDefinedTableFunction & rhs) const
  {
    if (!(name == rhs.name))
      return false;
    if (!(sizerType == rhs.sizerType))
      return false;
    if (!(sizerArgPos == rhs.sizerArgPos))
      return false;
    if (!(inputArgTypes == rhs.inputArgTypes))
      return false;
    if (!(outputArgTypes == rhs.outputArgTypes))
      return false;
    if (!(sqlArgTypes == rhs.sqlArgTypes))
      return false;
    return true;
  }
  bool operator != (const TUserDefinedTableFunction &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TUserDefinedTableFunction & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(TUserDefinedTableFunction &a, TUserDefinedTableFunction &b);

std::ostream& operator<<(std::ostream& out, const TUserDefinedTableFunction& obj);



#endif
